name: CI
on:
  pull_request:
  push:
    branches: [dev, main]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Prettier (check)
        run: pnpm format

      - name: ESLint
        run: pnpm lint

      - name: Build
        env:
          NODE_ENV: production
        run: pnpm build
